#ifndef QUICKTIMETOOLS_H
#define QUICKTIMETOOLS_H

enum QuicktimeTools_ErrorOrWarning
{
	QTT_NO_ERRORS_OR_WARNINGS = 0,

	QTT_GENERIC_ERROR = -1,

	QTT_NEED_QUICKTIME = -1000,
	QTT_UNABLE_TO_READ,
	QTT_UNABLE_TO_ENCODE,

	QTT_WARNINGS_WHILE_ENCODING = -2000
};

#endif // QUICKTIMETOOLS_H