#ifndef WINRTHELPER_H
#define WINRTHELPER_H

#if UNITY_WINRT

#	if UNITY_METRO_VS2012
#		if defined(__arm__)
#			include "build/temp/MetroSupport/metroARM/AutoGeneratedFuncDefs.h"
#		else
#			include "build/temp/MetroSupport/metro32/AutoGeneratedFuncDefs.h"
#		endif
#	elif UNITY_METRO_VS2013
#		if defined(__arm__)
#			include "build/temp/MetroSupport/metroBlueARM/AutoGeneratedFuncDefs.h"
#		else
#			include "build/temp/MetroSupport/metroBlue32/AutoGeneratedFuncDefs.h"
#		endif
#	elif UNITY_WP8
#	include "build/temp/WP8Support/AutoGeneratedFuncDefs.h"
#	endif
#endif


inline long long* GetWinRTFuncDefsPointers()
{
	return (long long*)UnityEngineDelegates::FunctionDefsDictionary::GetPointers();
}

#endif
