// This file is automatically generated with Runtime/GfxDevice/opengl/GenerateGLExtensionDef.pl.
// It is generated from GLExtensionDefs.txt


//Tex coords
DEF (PFNGLACTIVETEXTUREPROC, glActiveTextureARB);
#define glActiveTextureARB UNITYGL_glActiveTextureARB
DEF (PFNGLCLIENTACTIVETEXTUREPROC, glClientActiveTextureARB);
#define glClientActiveTextureARB UNITYGL_glClientActiveTextureARB
DEF (PFNGLMULTITEXCOORD3FPROC, glMultiTexCoord3fARB);
#define glMultiTexCoord3fARB UNITYGL_glMultiTexCoord3fARB
DEF (PFNGLMULTITEXCOORD4FPROC, glMultiTexCoord4fARB);
#define glMultiTexCoord4fARB UNITYGL_glMultiTexCoord4fARB
DEF (PFNGLMULTITEXCOORD3FVPROC, glMultiTexCoord3fvARB);
#define glMultiTexCoord3fvARB UNITYGL_glMultiTexCoord3fvARB
DEF (PFNGLMULTITEXCOORD4FVPROC, glMultiTexCoord4fvARB);
#define glMultiTexCoord4fvARB UNITYGL_glMultiTexCoord4fvARB

//Blending
DEF (PFNGLBLENDCOLORPROC, glBlendColor);
#define glBlendColor UNITYGL_glBlendColor
DEF (PFNGLBLENDFUNCSEPARATEEXTPROC, glBlendFuncSeparateEXT);
#define glBlendFuncSeparateEXT UNITYGL_glBlendFuncSeparateEXT
DEF (PFNGLBLENDEQUATIONPROC, glBlendEquation);
#define glBlendEquation UNITYGL_glBlendEquation
DEF (PFNGLBLENDEQUATIONSEPARATEEXTPROC, glBlendEquationSeparateEXT);
#define glBlendEquationSeparateEXT UNITYGL_glBlendEquationSeparateEXT

// ARB_VP, ARB FP
DEF (PFNGLDELETEPROGRAMSARBPROC, glDeleteProgramsARB);
#define glDeleteProgramsARB UNITYGL_glDeleteProgramsARB
DEF (PFNGLGENPROGRAMSARBPROC, glGenProgramsARB);
#define glGenProgramsARB UNITYGL_glGenProgramsARB
DEF (PFNGLBINDPROGRAMARBPROC, glBindProgramARB);
#define glBindProgramARB UNITYGL_glBindProgramARB
DEF (PFNGLPROGRAMLOCALPARAMETER4FVARBPROC, glProgramLocalParameter4fvARB);
#define glProgramLocalParameter4fvARB UNITYGL_glProgramLocalParameter4fvARB
DEF (PFNGLPROGRAMENVPARAMETER4FVARBPROC, glProgramEnvParameter4fvARB);
#define glProgramEnvParameter4fvARB UNITYGL_glProgramEnvParameter4fvARB
DEF (PFNGLPROGRAMLOCALPARAMETER4FARBPROC, glProgramLocalParameter4fARB);
#define glProgramLocalParameter4fARB UNITYGL_glProgramLocalParameter4fARB
DEF (PFNGLPROGRAMENVPARAMETER4FARBPROC, glProgramEnvParameter4fARB);
#define glProgramEnvParameter4fARB UNITYGL_glProgramEnvParameter4fARB
DEF (PFNGLPROGRAMSTRINGARBPROC, glProgramStringARB);
#define glProgramStringARB UNITYGL_glProgramStringARB
DEF (PFNGLGETPROGRAMENVPARAMETERFVARBPROC, glGetProgramEnvParameterfvARB);
#define glGetProgramEnvParameterfvARB UNITYGL_glGetProgramEnvParameterfvARB

// Textures
DEF (PFNGLCOMPRESSEDTEXIMAGE2DARBPROC, glCompressedTexImage2DARB);
#define glCompressedTexImage2DARB UNITYGL_glCompressedTexImage2DARB
DEF (PFNGLCOMPRESSEDTEXSUBIMAGE2DARBPROC, glCompressedTexSubImage2DARB);
#define glCompressedTexSubImage2DARB UNITYGL_glCompressedTexSubImage2DARB
DEF (PFNGLTEXIMAGE3DPROC, glTexImage3D);
#define glTexImage3D UNITYGL_glTexImage3D

#if UNITY_OSX
// Apple fences
DEF (PFNGLGENFENCESAPPLEPROC, glGenFencesAPPLE);
#define glGenFencesAPPLE UNITYGL_glGenFencesAPPLE
DEF (PFNGLDELETEFENCESAPPLEPROC, glDeleteFencesAPPLE);
#define glDeleteFencesAPPLE UNITYGL_glDeleteFencesAPPLE
DEF (PFNGLSETFENCEAPPLEPROC, glSetFenceAPPLE);
#define glSetFenceAPPLE UNITYGL_glSetFenceAPPLE
DEF (PFNGLISFENCEAPPLEPROC, glIsFenceAPPLE);
#define glIsFenceAPPLE UNITYGL_glIsFenceAPPLE
DEF (PFNGLTESTFENCEAPPLEPROC, glTestFenceAPPLE);
#define glTestFenceAPPLE UNITYGL_glTestFenceAPPLE
DEF (PFNGLFINISHFENCEAPPLEPROC, glFinishFenceAPPLE);
#define glFinishFenceAPPLE UNITYGL_glFinishFenceAPPLE
DEF (PFNGLFINISHOBJECTAPPLEPROC, glFinishObjectAPPLE);
#define glFinishObjectAPPLE UNITYGL_glFinishObjectAPPLE
DEF (PFNGLTESTOBJECTAPPLEPROC, glTestObjectAPPLE);
#define glTestObjectAPPLE UNITYGL_glTestObjectAPPLE

// APPLE_flush_buffer_range
DEF (PFNGLBUFFERPARAMETERIAPPLEPROC, glBufferParameteriAPPLE);
#define glBufferParameteriAPPLE UNITYGL_glBufferParameteriAPPLE
DEF (PFNGLFLUSHMAPPEDBUFFERRANGEAPPLEPROC, glFlushMappedBufferRangeAPPLE);
#define glFlushMappedBufferRangeAPPLE UNITYGL_glFlushMappedBufferRangeAPPLE
#endif

// ARB_vertex_buffer_object
DEF (PFNGLGENBUFFERSARBPROC, glGenBuffersARB);
#define glGenBuffersARB UNITYGL_glGenBuffersARB
DEF (PFNGLDELETEBUFFERSARBPROC, glDeleteBuffersARB);
#define glDeleteBuffersARB UNITYGL_glDeleteBuffersARB
DEF (PFNGLBUFFERDATAARBPROC, glBufferDataARB);
#define glBufferDataARB UNITYGL_glBufferDataARB
DEF (PFNGLBINDBUFFERARBPROC, glBindBufferARB);
#define glBindBufferARB UNITYGL_glBindBufferARB
DEF (PFNGLMAPBUFFERARBPROC, glMapBufferARB);
#define glMapBufferARB UNITYGL_glMapBufferARB
DEF (PFNGLUNMAPBUFFERARBPROC, glUnmapBufferARB);
#define glUnmapBufferARB UNITYGL_glUnmapBufferARB
DEF (PFNGLBUFFERSUBDATAARBPROC, glBufferSubDataARB);
#define glBufferSubDataARB UNITYGL_glBufferSubDataARB

// ARB_map_buffer_range
DEF (PFNGLMAPBUFFERRANGEPROC, glMapBufferRange);
#define glMapBufferRange UNITYGL_glMapBufferRange

// ARB_vertex_program
DEF (PFNGLGETPROGRAMIVARBPROC, glGetProgramivARB);
#define glGetProgramivARB UNITYGL_glGetProgramivARB
DEF (PFNGLVERTEXATTRIBPOINTERARBPROC, glVertexAttribPointerARB);
#define glVertexAttribPointerARB UNITYGL_glVertexAttribPointerARB
DEF (PFNGLENABLEVERTEXATTRIBARRAYARBPROC, glEnableVertexAttribArrayARB);
#define glEnableVertexAttribArrayARB UNITYGL_glEnableVertexAttribArrayARB
DEF (PFNGLDISABLEVERTEXATTRIBARRAYARBPROC, glDisableVertexAttribArrayARB);
#define glDisableVertexAttribArrayARB UNITYGL_glDisableVertexAttribArrayARB

// ARB_occlusion query
DEF (PFNGLGENQUERIESARBPROC, glGenQueriesARB);
#define glGenQueriesARB UNITYGL_glGenQueriesARB
DEF (PFNGLBEGINQUERYARBPROC, glBeginQueryARB);
#define glBeginQueryARB UNITYGL_glBeginQueryARB
DEF (PFNGLENDQUERYARBPROC, glEndQueryARB);
#define glEndQueryARB UNITYGL_glEndQueryARB
DEF (PFNGLGETQUERYOBJECTIVARBPROC, glGetQueryObjectivARB);
#define glGetQueryObjectivARB UNITYGL_glGetQueryObjectivARB
DEF (PFNGLGETQUERYOBJECTUIVARBPROC, glGetQueryObjectuivARB);
#define glGetQueryObjectuivARB UNITYGL_glGetQueryObjectuivARB
DEF (PFNGLDELETEQUERIESARBPROC, glDeleteQueriesARB);
#define glDeleteQueriesARB UNITYGL_glDeleteQueriesARB

// EXT_timer query
DEF (PFNGLGETQUERYOBJECTI64VEXTPROC, glGetQueryObjecti64vEXT);
#define glGetQueryObjecti64vEXT UNITYGL_glGetQueryObjecti64vEXT
DEF (PFNGLGETQUERYOBJECTUI64VEXTPROC, glGetQueryObjectui64vEXT);
#define glGetQueryObjectui64vEXT UNITYGL_glGetQueryObjectui64vEXT

// ARB_sync
DEF (PFNGLFENCESYNCPROC, glFenceSync);
#define glFenceSync UNITYGL_glFenceSync
DEF (PFNGLDELETESYNCPROC, glDeleteSync);
#define glDeleteSync UNITYGL_glDeleteSync
DEF (PFNGLCLIENTWAITSYNCPROC, glClientWaitSync);
#define glClientWaitSync UNITYGL_glClientWaitSync

// GLSL
DEF (PFNGLCREATEPROGRAMOBJECTARBPROC, glCreateProgramObjectARB);
#define glCreateProgramObjectARB UNITYGL_glCreateProgramObjectARB
DEF (PFNGLCREATESHADEROBJECTARBPROC, glCreateShaderObjectARB);
#define glCreateShaderObjectARB UNITYGL_glCreateShaderObjectARB
DEF (PFNGLSHADERSOURCEARBPROC, glShaderSourceARB);
#define glShaderSourceARB UNITYGL_glShaderSourceARB
DEF (PFNGLCOMPILESHADERARBPROC, glCompileShaderARB);
#define glCompileShaderARB UNITYGL_glCompileShaderARB
DEF (PFNGLATTACHOBJECTARBPROC, glAttachObjectARB);
#define glAttachObjectARB UNITYGL_glAttachObjectARB
DEF (PFNGLLINKPROGRAMARBPROC, glLinkProgramARB);
#define glLinkProgramARB UNITYGL_glLinkProgramARB
DEF (PFNGLUSEPROGRAMOBJECTARBPROC, glUseProgramObjectARB);
#define glUseProgramObjectARB UNITYGL_glUseProgramObjectARB
DEF (PFNGLDELETEOBJECTARBPROC, glDeleteObjectARB);
#define glDeleteObjectARB UNITYGL_glDeleteObjectARB
DEF (PFNGLGETHANDLEARBPROC, glGetHandleARB);
#define glGetHandleARB UNITYGL_glGetHandleARB
DEF (PFNGLGETINFOLOGARBPROC, glGetInfoLogARB);
#define glGetInfoLogARB UNITYGL_glGetInfoLogARB
DEF (PFNGLGETACTIVEATTRIBARBPROC, glGetActiveAttribARB);
#define glGetActiveAttribARB UNITYGL_glGetActiveAttribARB
DEF (PFNGLGETACTIVEUNIFORMARBPROC, glGetActiveUniformARB);
#define glGetActiveUniformARB UNITYGL_glGetActiveUniformARB
DEF (PFNGLGETUNIFORMLOCATIONARBPROC, glGetUniformLocationARB);
#define glGetUniformLocationARB UNITYGL_glGetUniformLocationARB
DEF (PFNGLGETATTRIBLOCATIONARBPROC, glGetAttribLocationARB);
#define glGetAttribLocationARB UNITYGL_glGetAttribLocationARB
DEF (PFNGLGETOBJECTPARAMETERIVARBPROC, glGetObjectParameterivARB);
#define glGetObjectParameterivARB UNITYGL_glGetObjectParameterivARB
DEF (PFNGLUNIFORM1FVARBPROC, glUniform1fvARB);
#define glUniform1fvARB UNITYGL_glUniform1fvARB
DEF (PFNGLUNIFORM2FVARBPROC, glUniform2fvARB);
#define glUniform2fvARB UNITYGL_glUniform2fvARB
DEF (PFNGLUNIFORM3FVARBPROC, glUniform3fvARB);
#define glUniform3fvARB UNITYGL_glUniform3fvARB
DEF (PFNGLUNIFORM4FVARBPROC, glUniform4fvARB);
#define glUniform4fvARB UNITYGL_glUniform4fvARB
DEF (PFNGLUNIFORMMATRIX4FVARBPROC, glUniformMatrix4fvARB);
#define glUniformMatrix4fvARB UNITYGL_glUniformMatrix4fvARB
DEF (PFNGLUNIFORM1IVARBPROC, glUniform1ivARB);
#define glUniform1ivARB UNITYGL_glUniform1ivARB
DEF (PFNGLUNIFORM2IVARBPROC, glUniform2ivARB);
#define glUniform2ivARB UNITYGL_glUniform2ivARB
DEF (PFNGLUNIFORM3IVARBPROC, glUniform3ivARB);
#define glUniform3ivARB UNITYGL_glUniform3ivARB
DEF (PFNGLUNIFORM4IVARBPROC, glUniform4ivARB);
#define glUniform4ivARB UNITYGL_glUniform4ivARB

#if UNITY_WIN
// Windows P-buffers
DEF (PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
#define wglChoosePixelFormatARB UNITYGL_wglChoosePixelFormatARB
DEF (PFNWGLGETPIXELFORMATATTRIBIVARBPROC, wglGetPixelFormatAttribivARB);
#define wglGetPixelFormatAttribivARB UNITYGL_wglGetPixelFormatAttribivARB
DEF (PFNWGLGETEXTENSIONSSTRINGARBPROC, wglGetExtensionsStringARB);
#define wglGetExtensionsStringARB UNITYGL_wglGetExtensionsStringARB
DEF (PFNWGLGETEXTENSIONSSTRINGEXTPROC, wglGetExtensionsStringEXT);
#define wglGetExtensionsStringEXT UNITYGL_wglGetExtensionsStringEXT

// Windows VSync
DEF (PFNWGLSWAPINTERVALEXTPROC, wglSwapIntervalEXT);
#define wglSwapIntervalEXT UNITYGL_wglSwapIntervalEXT
#endif

// GL_EXT_framebuffer_object
DEF (PFNGLGENFRAMEBUFFERSEXTPROC, glGenFramebuffersEXT);
#define glGenFramebuffersEXT UNITYGL_glGenFramebuffersEXT
DEF (PFNGLBINDFRAMEBUFFEREXTPROC, glBindFramebufferEXT);
#define glBindFramebufferEXT UNITYGL_glBindFramebufferEXT
DEF (PFNGLGENRENDERBUFFERSEXTPROC, glGenRenderbuffersEXT);
#define glGenRenderbuffersEXT UNITYGL_glGenRenderbuffersEXT
DEF (PFNGLBINDRENDERBUFFEREXTPROC, glBindRenderbufferEXT);
#define glBindRenderbufferEXT UNITYGL_glBindRenderbufferEXT
DEF (PFNGLRENDERBUFFERSTORAGEEXTPROC, glRenderbufferStorageEXT);
#define glRenderbufferStorageEXT UNITYGL_glRenderbufferStorageEXT
DEF (PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC, glFramebufferRenderbufferEXT);
#define glFramebufferRenderbufferEXT UNITYGL_glFramebufferRenderbufferEXT
DEF (PFNGLFRAMEBUFFERTEXTURE2DEXTPROC, glFramebufferTexture2DEXT);
#define glFramebufferTexture2DEXT UNITYGL_glFramebufferTexture2DEXT
DEF (PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC, glCheckFramebufferStatusEXT);
#define glCheckFramebufferStatusEXT UNITYGL_glCheckFramebufferStatusEXT
DEF (PFNGLDELETEFRAMEBUFFERSEXTPROC, glDeleteFramebuffersEXT);
#define glDeleteFramebuffersEXT UNITYGL_glDeleteFramebuffersEXT
DEF (PFNGLDELETERENDERBUFFERSEXTPROC, glDeleteRenderbuffersEXT);
#define glDeleteRenderbuffersEXT UNITYGL_glDeleteRenderbuffersEXT
DEF (PFNGLGENERATEMIPMAPEXTPROC, glGenerateMipmapEXT);
#define glGenerateMipmapEXT UNITYGL_glGenerateMipmapEXT

// GL_ARB_draw_buffers
DEF (PFNGLDRAWBUFFERSARBPROC, glDrawBuffersARB);
#define glDrawBuffersARB UNITYGL_glDrawBuffersARB

// GL_EXT_framebuffer_blit
DEF (PFNGLBLITFRAMEBUFFEREXTPROC, glBlitFramebufferEXT);
#define glBlitFramebufferEXT UNITYGL_glBlitFramebufferEXT

// GL_EXT_framebuffer_multisample
DEF (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC, glRenderbufferStorageMultisampleEXT);
#define glRenderbufferStorageMultisampleEXT UNITYGL_glRenderbufferStorageMultisampleEXT

// Separate stencil in GL2.0
DEF (PFNGLSTENCILFUNCSEPARATEPROC, glStencilFuncSeparate);
#define glStencilFuncSeparate UNITYGL_glStencilFuncSeparate
DEF (PFNGLSTENCILOPSEPARATEPROC, glStencilOpSeparate);
#define glStencilOpSeparate UNITYGL_glStencilOpSeparate
