
//THIS FILE IS AUTOGENERATED BY build.pl --prepare	
using System.Collections.Generic;

namespace UnityEditor
{
	internal static class AssembliesShippedWithWebPlayerProvider
	{
		static public string[] ProvideAsArray()
		{
			return new[] { "mscorlib.dll","System.dll","System.Core.dll","Mono.Security.dll" };
		}
	}
}